### ISSUE TITLE
Refactor for better re-use?

### ISSUE THREAD

**Issue by dkolepp** [sirosen/check-jsonschema#23]
## Refactor/Feature Request
I'd like to see the `run` method return a returncode, and let `main` exit appropriately based on the return code provided by the `run` method.
https://github.com/sirosen/check-jsonschema/blob/42ad7416d2bbe133fa87db0e8a0559df534f35ea/src/check_jsonschema/__init__.py#L16

## Use case
I have a strange use case where I need to validate a YAML file, but that YAML is a build artifact that is generated from a Jinja2 template (that is kept in source control).  I need to do some pre-processing (with a wrapper script) - and then I want to use the `check-jsonschema` library (SchemaChecker) with arguments constructed from the arguments passes to the wrapper script (which is also a pre-commit compatible script).

Because the `SchemaChecker` issues the `sys.exit` command - I can't examine the return code and take action based on that.  Embedding the SchemaChecker causes the wrapper script to stop.

If the `sys.exit` call was moved from SchemaChecker - to `main` - then the SchemaChecker could be used independently.

## Note/Workaround
I *can* get around this - by using the `subprocess` module and calling `check-jsonschema` as a CLI subprocess, and then examine the return code.

**Comment by sirosen** [comment]
> I _can_ get around this - by using the `subprocess` module and calling `check-jsonschema` as a CLI subprocess, and then examine the return code.

This would be my recommendation for today, even though it's slower.

`check-jsonschema` provides a CLI tool. The internals are not documented and I don't consider them part of its public interface. I'd consider it pretty likely that any code which imports from `check_jsonschema` could be broken in the future.

---

That said, I do understand that you may want to be able to invoke `check-jsonschema` within a python process _without_ a subprocess invocation and new python interpreter start.

I'll think about whether or not a single public interface method would be reasonable at this point in time, e.g.
```python
from check_jsonschema import api

api.main(["--schemafile", ...])
```

While I think about this, and in order to see if it's necessary, what makes you want to use `check-jsonschema` rather than the underlying `jsonschema` library? Presumably you could use `ruamel.yaml` to load the file and `jsonschema` to check the loaded data against a schema.

The code in this repo could be used as a model or guidance. This repo is Apache 2.0 licensed -- meaning that it is free for redistribution and use in derivative works, provided you retain the license -- and there would be no issue with imitating many of the relatively generic parts of it without including the license.

**Comment by sirosen** [comment]
I'm inclined not to add any python interface for using this tool. It was designed first and foremost as a pre-commit hook, and only secondarily (and for easy testing) as a CLI utility.

I'm going to close this, but it's not necessarily the final word on it. If someone comes back with a clear reason why it should be supported and explains why neither `jsonschema` nor `subprocess.run` invocation is sufficient, I'm happy to listen.
