### ISSUE TITLE
pre-commit fails when cache is missing

### ISSUE THREAD

**Issue by foolioo** [sirosen/check-jsonschema#7]
having 10 files that are checked using the pre-commit hook, on a fresh run (cache directory does not exist) the check fails (but the cache is populated with the schemas) but when running pre-commit again, everything passes ok.

while trying to debug, i noticed that pre-commit calls the 10 files in 2 batches and thus invokes check-jsonschema twice.
i can [reproduce it when using pre-commit](https://github.com/foolioo/check-jsonschema/tree/reproduce), but it does not happen when using check-jsonschema directly.

how to reproduce:
1. [checkout the branch](https://github.com/foolioo/check-jsonschema/tree/reproduce)
2. delete `jsonschema_validate` cache directory
3. run `pre-commit run --all-files --verbose`

**Comment by sirosen** [comment]
If I had to guess, based on you seeing two invocations:
- pre-commit may shard long file lists into multiple invocations (e.g. one per core). If so, it's a feature I didn't know about. I'll have to read up to see if that's the case.
- The cached_open helper is not written to be concurrency safe. I didn't really think it needed to be, but I can fix it to write a temp file and rename, so that the desirable cache file is not opened twice for writing.

Ideally, I'd like to understand what's happening better before taking any action.

**Comment by foolioo** [comment]
@sirosen: thank you. right now, the quickest bypass is to run pre-commit twice

**Comment by foolioo** [comment]
@sirosen: solved by using [`require_serial: true`](https://pre-commit.com/#hooks-require_serial)
